
#### general settings

name: 01_IRN_DB_x4_scratch_DIV2K
use_tb_logger: true
model: PAMI # CVPR
distortion: sr
scale: 4
gpu_ids: [3] #[1,3,4]


#### datasets
phase: train
only_gen_immunized: 0.0
eval_dataset: COCO
eval_kind: inpainting
eval_attack: NOATK
dataset_name: Rerun
#phase: test

datasets:
  train:
    name: Rerun
    mode: LQGT
    dataroot_GT: /home/groupshare//COCOdataset/train2017                                   # COCO
    dataroot_LQ: ~ # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader

    use_shuffle: true
    n_workers: 1 # per GPU

    batch_size: 3 # 4
    GT_size: 512 # 608

    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: /home/qichaoying/Downloads/Invertible-Image-Rescaling-master/icassp_real/images
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader


#### network structures

network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [6, 6]
  scale: 4
  init: xavier


#### path

path:


  pretrain_model: ~
  #########################
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss

train:
  using_self_defined_dataset: 0.0
  new_task: 1.0  # 0:imuge 1:outward imuge
  task_name: ImugeV2 # ImugeV2 # CropLocalize # RHI3
  debug_mode: 0
  save_to_latest: 1.0
  load: 0.0
  lr_G: !!float 1e-4   # 2e-5
  lr_D: !!float 1e-4
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999
  niter: 500000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [20000, 40000, 60000, 80000 ,100000,120000,140000,160000,180000,200000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  manual_seed: 12

  val_freq: !!float 5e3

  lambda_fit_forw: 16.
  lambda_rec_back: 1
  lambda_ce_forw: 1
  weight_decay_G: !!float 1e-5
  gradient_clipping: 10

  current_step: 0


#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
